### PR TITLE
mock PR (to get your attention)

### PR DESCRIPTION
**Pull request by luzpaz**
@caceres I opened a mock PR just to get your attention about https://freecadweb.org/tracker/view.php?id=2335
Do you still have a fix for this somewhere?
(I've been trying to reach you unsuccessfully via the FreeCAD tracker and the forums. Sorry for this unfortunate and clunky way of getting your attention. Thanks in advance!

### CODE REVIEW

**Comment by caceres** [comment]
Buenos días @luzpaz 
I'm afraid 'no'. I don't still have a solution for this. 
With my level, the excursion in bug tracker is not a good idea.
Hoewer, I feel more comfortable with the macros, and I hope to realize one soon.
Thank you for your interest
Hasta pronto

**Comment by luzpaz** [comment]
@caceres thanks for your reply. can you signal me if you reailze a macro for this?

**Comment by caceres** [comment]
No. The macro is about other question

**Comment by luzpaz** [comment]
other question? which question?

**Comment by caceres** [comment]
https://forum.freecadweb.org/viewtopic.php?f=23&t=19120
It will be 'slopedPlanesMacro'
The launching will be the day after the release of FreeCAD 0.18  (QT5 y python3 from the beginning).
The first version (pre-alfa version) will be the engine and a little more. A lot of improvements are very delayed.
This basic version has four thousand lines (4000 lines, oh my god !!!!)
It's a crazy issue. You can't find in the community any solution about this with a minimum quality.
My proposal is written from scratch and, of course, there isn't any mathematical foundation which supports this solution. The first checks will be very fun. 
Adios

**Comment by luzpaz** [comment]
>  This basic version has four thousand lines (4000 lines, oh my god !!!!)

@caceres perhaps you could let the community test it? Who knows when 0.18 will be released! 🤣

**Pull request closed without merging**
